version: "3.7"
# 管理的服务
services:
  # 服务名
  smtp.proxy:
    container_name: smtp.proxy
    # 重启策略
    restart: always
    # 镜像
    image: "iuupub/smtp.proxy:1.0.3"
    # 端口映射
    ports:
      - "9080:80"
    # 环境变量
    environment:
      - SMTP_PROXY_TOKEN=${SMTP_PROXY_TOKEN}
      - SMTP_PROXY_HOST=${SMTP_PROXY_HOST}
      - SMTP_PROXY_PORT=${SMTP_PROXY_PORT}
      - SMTP_PROXY_USERNAME=${SMTP_PROXY_USERNAME}
      - SMTP_PROXY_PASSWORD=${SMTP_PROXY_PASSWORD}
      - TZ=Asia/Shanghai
    entrypoint: ["/var/bin/smtp.proxy.server.app"]